version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
      - ./icons:/app/public/icons
    environment:
      - PUID=1000
      - PGID=1000
      - USERNAME_CLOUD=$USERNAME_CLOUD
      - PASSWORD_CLOUD=$PASSWORD_CLOUD
    restart: unless-stopped
