---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

title: Hacker Cloud

background: /images/background.png

  #background:
  # image: /images/background.png
  # blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  # saturate: 60 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  # brightness: 60 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  # opacity: 80 # 0-100
